# examples/complex-document-with-bibliography.yml
# Example: Academic paper with bibliography and supplementary materials
# Shows how to build complex documents that may need specific packages

name: Build Academic Paper with Supplementary Materials

on:
  push:
    branches: [main, submission]
  pull_request:
    branches: [main]

jobs:
  # Build the main academic paper
  build-paper:
    name: Build Academic Paper
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Build paper
        id: paper
        uses: AlaCodon/latexonfly@main
        with:
          entry_tex: "paper.tex"
          working_directory: "src"             # LaTeX files in src/ directory
          engine: "pdflatex"                  # Most journals prefer pdflatex
          texlive_scheme: "full"              # Academic papers often need many packages
          timeout_minutes: "45"               # Extended timeout for complex documents
          keep_build_deps: "true"             # Keep for reproducibility

  # Optional: Build supplementary materials
  build-supplementary:
    name: Build Supplementary Materials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Build supplementary
        id: supplementary
        uses: AlaCodon/latexonfly@main
        with:
          entry_tex: "supplementary.tex"
          working_directory: "supplementary"
          engine: "pdflatex"
          texlive_scheme: "basic"             # Supplementary usually simpler

  # Create submission package for journal submission
  create-submission-package:
    name: Create Submission Package
    needs: [build-paper, build-supplementary]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/submission'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Download paper artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: latex-pdfs
          path: paper-pdfs/

      - name: Download supplementary artifacts  
        uses: actions/download-artifact@v4.1.8
        with:
          name: latex-pdfs
          path: supplementary-pdfs/

      - name: Prepare submission files
        run: |
          mkdir -p submission-package
          
          # Copy PDFs with proper names
          cp paper-pdfs/*.pdf submission-package/main-manuscript.pdf 2>/dev/null || true
          cp supplementary-pdfs/*.pdf submission-package/supplementary-materials.pdf 2>/dev/null || true

          # Copy source files if required by journal
          cp -r src/*.tex submission-package/ 2>/dev/null || true
          cp -r src/*.bib submission-package/ 2>/dev/null || true

          # Create submission README
          cat > submission-package/submission-readme.txt << 'SUBMISSION_EOF'
          Submission Package Contents:
          - main-manuscript.pdf: Main paper
          - supplementary-materials.pdf: Supplementary materials
          - Source LaTeX files (if required)

          Generated: $(date)
          Commit: ${GITHUB_SHA}
          SUBMISSION_EOF

      - name: Create submission release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd submission-package
          TAG="submission-$(date -u +'%Y%m%d-%H%M%S')"

          tar -czf submission-package.tar.gz *

          gh release create "$TAG" \
            --title "Journal Submission Package - $(date -u +'%Y-%m-%d')" \
            --target "$GITHUB_SHA" \
            --notes "Complete submission package with paper and supplementary materials" \
            submission-package.tar.gz \
            main-manuscript.pdf \
            supplementary-materials.pdf
